global:
  scrape_interval: 10s
  evaluation_interval: 10s

scrape_configs:
  - job_name: satsrover_indexer
    metrics_path: /metrics
    static_configs:
      - targets: ["host.docker.internal:9108"]
